---
ID: "ea686db1-99d7-45f3-8306-c6ac1326c66c"
Parent: "608917de-e7ac-48d0-acc8-4aae9797fbe3"
Template: "608917de-e7ac-48d0-acc8-4aae9797fbe3"
Path: /sitecore/client/Your Apps/Data Import/Renderings/version 1/Behaviors/CustomMultiSelectList/CustomMultiSelectList/__Standard Values
DB: core
SharedFields:
- ID: "8b400719-b932-4230-b5f9-6e9ba2ca07a7"
  Hint: PageScriptFileName
  Value: /sitecore/shell/client/Applications/XCDataImport/version 1/Behaviors/CustomMultiSelectList.js
- ID: "b5077812-5551-4c46-9bba-4cb190ccf253"
  Hint: Name
  Value: CustomMultiSelectList
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20130430T142314
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\admin
