---
ID: "343b476c-9d57-4fd4-8e7b-63749298e6c3"
Parent: "9b725899-252b-4bbb-9889-f810e7ba0cdb"
Template: "e35eaa2d-edea-431c-a9e6-488272b53782"
Path: "/sitecore/client/Your Apps/Data Import/Dashboard/Sitecore Data Import - 81/Existing Mappings/Existing Batch Mappings/PageSettings"
DB: core
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20160303T223706Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\admin
