---
ID: "560adec9-7154-4806-ac53-eb65102f869d"
Parent: "3b13cfdf-d81e-4479-a755-f1337ed06210"
Template: "e35eaa2d-edea-431c-a9e6-488272b53782"
Path: /sitecore/client/Your Apps/Data Import/Dashboard/Sitecore Data Import/Existing Mappings/Create Mapping/PageSettings
DB: core
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20170524T160343Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\Admin
