---
ID: "7981abca-c14f-4bee-96fd-dc3e16a9ee41"
Parent: "df2723b0-cab8-4086-8e8b-73aefb079164"
Template: "e35eaa2d-edea-431c-a9e6-488272b53782"
Path: /sitecore/client/Your Apps/Data Import/v2/NonSc/Create Template Mapping/PageSettings
DB: core
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20160303T223706Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\admin
