---
ID: "1c5c6e53-180a-4fb2-b6d9-4de55622bcec"
Parent: "9f745642-fd57-4076-bbb6-a5316d0271d2"
Template: "e35eaa2d-edea-431c-a9e6-488272b53782"
Path: /sitecore/client/Your Apps/Data Import/Dashboard/Sitecore Data Import/Actions/Delete Mapping/PageSettings
DB: core
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20170708T161402Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\Admin
