---
ID: "8d6614ee-319c-44ed-918c-38fe671aa026"
Parent: "d4cabaef-f4ea-4167-a633-82f45e230860"
Template: "f90052a5-b4e6-4e6d-9812-1e1b88a6fcea"
Path: /sitecore/client/Business Component Library/version 1/Layouts/Renderings/Resources/Rule/Rules/Actions/SetApplicationAttribute
DB: core
SharedFields:
- ID: "0b8b930b-8916-4462-bd4d-700303eadfd6"
  Hint: Code
  Value: 
Languages:
- Language: da
  Fields:
  - ID: "b5e02ad9-d56f-4c41-a065-a133db87bdeb"
    Hint: __Display name
    Value: SetApplicationAttribute
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20161221T104107Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\admin
    - ID: "eeb36a3b-40d9-4af5-862a-de257b84dca3"
      Hint: Text
      Value: "angiv applikationsattribut [name,,,name] til [value,,,value]"
- Language: "de-DE"
  Fields:
  - ID: "b5e02ad9-d56f-4c41-a065-a133db87bdeb"
    Hint: __Display name
    Value: FestlegenAnwendungAttribut
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20161221T104627Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\admin
    - ID: "eeb36a3b-40d9-4af5-862a-de257b84dca3"
      Hint: Text
      Value: "Anwendungsattribut  [name,,,name] auf [value,,,value] einstellen"
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20130320T095225
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\admin
    - ID: "eeb36a3b-40d9-4af5-862a-de257b84dca3"
      Hint: Text
      Value: "set application attribute [name,,,name] to [value,,,value]"
- Language: "ja-JP"
  Fields:
  - ID: "b5e02ad9-d56f-4c41-a065-a133db87bdeb"
    Hint: __Display name
    Value: アプリケーションの属性を設定する
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20161221T105028Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\admin
    - ID: "eeb36a3b-40d9-4af5-862a-de257b84dca3"
      Hint: Text
      Value: "アプリケーションの [name,,,属性] に [value,,,値] を設定する"
